# Generated by Django 5.1.1 on 2024-11-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptiles', '0002_alter_reptile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reptile',
            name='species',
            field=models.CharField(default='Not defined', max_length=70),
            preserve_default=False,
        ),
    ]
